//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebDBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> departmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
